name: Truchita Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "TOKEN_DISCORD=${{ secrets.TOKEN_DISCORD }}" > .env

      - name: Reload bot with PM2
        run: |
          pm2 start src/init.js --name bot || pm2 restart bot
          pm2 save